# This file defines charm config options, and populates the Configure tab on Charmhub.
# If your charm does not require configuration options, delete this file entirely.
#
# See https://juju.is/docs/config for guidance.

options:
  # An example config option to customise the log level of the workload
  roles:
    description: |
      Configure which roles the worker takes as a comma-separated list of any subset of roles.

      The individual roles are: "compactor", "distributor", "ingester", "querier", "query-frontend", "store-gateway", "alertmanager", "overrides-exporter", "query-scheduler", "ruler", "all" (to include all of them).
    default: "all"
    type: string
