name: Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@main
    secrets: inherit

  terraform-fmt:
    # TODO move this to the centralized CI
    name: Terraform fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform fmt -check -recursive -diff

  terraform-test:
    # TODO move this to the centralized CI
    name: Terraform test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Setup operator environment (k8s)
        uses: charmed-kubernetes/actions-operator@main
        with:
          juju-channel: 3.5/stable
          provider: microk8s
          channel: 1.30-strict/stable
          microk8s-group: snap_microk8s
          microk8s-addons: "hostpath-storage dns"
          charmcraft-channel: "3.x/stable"
      - name: Run integration tests
        run: cd terraform && terraform init && terraform test
